apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
type: Opaque
data:
  google-client-id: MTA2ODE2Mjg4NTYzMw==
  google-client-secret: R09DU1BYLXhXZHg5N1J5Z1h6dFlUMnh6YkwxRWpTeEpPbHc=
  facebook-client-id: MTcwNTQyMzA4OTUxNjkzNg==
  facebook-client-secret: NTE0OTBlMTVkNzU1ZjY3NGFiYTI3ODc1NWQ2Y2FjNjM=